### ISSUE TITLE
Show list of TestFlight testers 

### ISSUE THREAD

**Issue by RishabhTayal** [RishabhTayal/ReviewMonitor#10]

**Comment by Eliottiosdevs** [comment]
This works, right?

**Comment by Eliottiosdevs** [comment]
![simulator screen shot - iphone x - 2018-01-06 at 10 16 02](https://user-images.githubusercontent.com/7842156/34638382-a01a141c-f2ca-11e7-88f4-74b265e91b76.png)

**Comment by RishabhTayal** [comment]
Closing this.  This has been already implemented.

**Comment by RishabhTayal** [comment]
There is bug related to this https://github.com/RishabhTayal/ReviewMonitor/issues/34
