### ISSUE TITLE
TestFlight (Onboarding) not working

### ISSUE THREAD

**Issue by CaptainYukinoshitaHachiman** [RishabhTayal/ReviewMonitor#17]
<img width="388" alt="image" src="https://user-images.githubusercontent.com/25654046/34322980-147135d4-e871-11e7-980e-15c72b60fef6.png">

**Comment by RishabhTayal** [comment]
I will take a look at it. Meanwhile if you send me your email, I will invite you. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by CaptainYukinoshitaHachiman** [comment]
yuweiqo@163.com
Thank you

**Comment by RishabhTayal** [comment]
I will keep the issue open so we can fix it. Thanks. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by askari01** [comment]
issue still exists, i tried yesterday and issue still exist. If you can send me invite

**Comment by RishabhTayal** [comment]
I will take some time out to take a look at this today. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by RishabhTayal** [comment]
@CaptainYukinoshitaHachiman, @askari01 this issue is fixed now. Please try again. Feel free to reopen it if Onboarding still doesn't work.

Thanks.

**Comment by CaptainYukinoshitaHachiman** [comment]
Seems to be fixed now 👍
