### ISSUE TITLE
Switch accounts 

### ISSUE THREAD

**Issue by dkhamsing** [RishabhTayal/ReviewMonitor#26]
I have multiple accounts under one ITC login, seems switching these accounts doesn’t work 🤔

**Comment by RishabhTayal** [comment]
Thanks for reporting. Will take a look.

**Comment by RishabhTayal** [comment]
Implemented in #29

**Comment by dkhamsing** [comment]
Thank you!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
