### ISSUE TITLE
Add support for TouchId/FaceId

### ISSUE THREAD

**Issue by RishabhTayal** [RishabhTayal/ReviewMonitor#41]
- Add option in settings to turn TouchId/FaceId on or off.
- Ask user to authenticate when launching the app.
- Ask for authentication if the app is in background for more than 2 minutes and then brought to foreground.

**Comment by Eliottiosdevs** [comment]
@RishabhTayal, I will try to take this one

**Comment by Eliottiosdevs** [comment]
Do you want to add it as security when opening app, or...?

**Comment by RishabhTayal** [comment]
Correct. Similar to the iTunes Connect app, when the user is logged in, the FaceId/TouchId should be enabled and user should be authenticated through that.

**Comment by Eliottiosdevs** [comment]
On it

**Comment by Eliottiosdevs** [comment]
Only option for 2 minutes inactivity or do we add an option in settings for it?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
