### ISSUE TITLE
Add instructions for setting up local API server.

### ISSUE THREAD

**Issue by RishabhTayal** [RishabhTayal/ReviewMonitor#44]
Add instructions in [README.MD](https://github.com/RishabhTayal/ReviewMonitor/blob/master/README.md)

**Comment by Eliottiosdevs** [comment]
Can be closed?

**Comment by RishabhTayal** [comment]
Not yet. I am planning to modify the iTC-api repo so any one can have a self hosted server on heroku. Once that change is done we need to add the instructions in this repo   

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Eliottiosdevs** [comment]
Ok
