### ISSUE TITLE
Show more app metadata on detail screen. 

### ISSUE THREAD

**Issue by RishabhTayal** [RishabhTayal/ReviewMonitor#48]
Should be able to show the data points from attached screenshot. 

![a279e6cf-0495-4964-bc89-fb95aa17f49a](https://user-images.githubusercontent.com/2100166/34463927-ad6b2644-ee31-11e7-9a0f-d05a48f245ae.jpeg)

**Comment by Eliottiosdevs** [comment]
On it!

**Comment by Eliottiosdevs** [comment]
What do you think if I add all data here? It seems to work with this start, will add rest now or do I need to change something? @RishabhTayal @KrauseFx https://i.imgur.com/vk9yWvW.jpg

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by RishabhTayal** [comment]
@Eliottiosdevs I think the metadata looks good. There needs to be some ui changes required.

**Comment by RishabhTayal** [comment]
I was thinking the UI should be more inline with the App Store page.

**Comment by Eliottiosdevs** [comment]
I will PR so and then you can edit. Is that ok?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by RishabhTayal** [comment]
Sounds good.

**Comment by Eliottiosdevs** [comment]
Thanks @RishabhTayal btw can you check slack? Stuck on something

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by delox** [comment]
LMK if help is still needed

**Comment by Eliottiosdevs** [comment]
@delox I will check tomorrow it’s 1 am

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by RishabhTayal** [comment]
@Eliottiosdevs Can you create a PR first on the https://github.com/RishabhTayal/itc-api server side code?

**Comment by Eliottiosdevs** [comment]
Ok

**Comment by Eliottiosdevs** [comment]
Am on it

**Comment by RishabhTayal** [comment]
@Eliottiosdevs Thanks.

**Comment by Eliottiosdevs** [comment]
@RishabhTayal Do you know that the testers screen and reviews doesn't work since the secure auth?
Team isn't passed...

**Comment by RishabhTayal** [comment]
@Eliottiosdevs I believe that bug was fixed in https://github.com/RishabhTayal/ReviewMonitor/pull/57. The testers screen is still not working. That was a bug prior to secure auth. There is an open issue #34   related to that. Not sure what the fix for the testers list bug is.

**Comment by RishabhTayal** [comment]
Testers bug is now fixed and merged to master.
