### ISSUE TITLE
Multiple account login shows wrong teams

### ISSUE THREAD

**Issue by RishabhTayal** [RishabhTayal/ReviewMonitor#53]
Logging in with different accounts shows wrong team names in the accounts list controller. 

![GitHawk Upload by RishabhTayal](https://i.imgur.com/QwoGAh6.jpg)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Eliottiosdevs** [comment]
I would like to check it

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by RishabhTayal** [comment]
@Eliottiosdevs This is now fixed.
