### ISSUE TITLE
Login suggestion id.apple.com/itunesconnect.apple.com

### ISSUE THREAD

**Issue by Eliottiosdevs** [RishabhTayal/ReviewMonitor#84]
In the suggestion bar show the logins from id.apple.com/itunesconnect.apple.com

**Comment by Eliottiosdevs** [comment]
idmsa.apple.com instead of id.apple.com

**Comment by Eliottiosdevs** [comment]
![img_3063](https://user-images.githubusercontent.com/7842156/34574086-a61bb032-f176-11e7-8306-d842212215d7.jpg)
![img_3064](https://user-images.githubusercontent.com/7842156/34574087-a6385444-f176-11e7-9271-b0b498d02e8c.JPG)

**Comment by RishabhTayal** [comment]
Looks like the auto fill suggestions can only be done for the 'associated' websites.

**Comment by RishabhTayal** [comment]
Closing this for now.
